# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EzshareSync < Formula
  desc "Synchronize files from EzShare Wi-Fi SD Card."
  homepage "https://github.com/haimgel/ezshare-sync"
  version "1.0.0"

  on_macos do
    url "https://github.com/haimgel/ezshare-sync/releases/download/v1.0.0/ezshare-sync_1.0.0_darwin_all.tar.gz"
    sha256 "0c596240e3cf26783ae0db060367abd0bbfd418b27fe6442e417701dd959931a"

    def install
      bin.install "ezshare-sync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.0.0/ezshare-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "b4bcd79ca33d6e13e34e61ae9df821a62f1403827ab2ffa74ac2adf0b7b8850a"
      def install
        bin.install "ezshare-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.0.0/ezshare-sync_1.0.0_linux_arm64.tar.gz"
      sha256 "e416a9cd6a3c93c51094c24bc02f7ac52270bb3e1de6463939b5915de98f1d2e"
      def install
        bin.install "ezshare-sync"
      end
    end
  end

  service do
    run [opt_bin/"ezshare-sync"]
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/ezshare-sync -h", 0)
  end
end
