# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EzshareSync < Formula
  desc "Synchronize files from EzShare Wi-Fi SD Card."
  homepage "https://github.com/haimgel/ezshare-sync"
  version "1.1.0"

  on_macos do
    url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.0/ezshare-sync_1.1.0_darwin_all.tar.gz"
    sha256 "42d2c6b9955a0629cc43456252015274b9b00376d90561cda6e0cf87d726a294"

    def install
      bin.install "ezshare-sync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.0/ezshare-sync_1.1.0_linux_amd64.tar.gz"
      sha256 "5aa8d26f6bd42cf830b32ba6c95fdc668c41f163a8f7f8392a2f17bb935a5d59"
      def install
        bin.install "ezshare-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.0/ezshare-sync_1.1.0_linux_arm64.tar.gz"
      sha256 "d5f8cb15b2c9efaf2cc215e2295662d4a78101256b1ddca303cb60d6ad032aa7"
      def install
        bin.install "ezshare-sync"
      end
    end
  end

  service do
    run [opt_bin/"ezshare-sync"]
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/ezshare-sync -h", 0)
  end
end
