# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EzshareSync < Formula
  desc "Synchronize files from EzShare Wi-Fi SD Card."
  homepage "https://github.com/haimgel/ezshare-sync"
  version "1.1.1"

  on_macos do
    url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.1/ezshare-sync_1.1.1_darwin_all.tar.gz"
    sha256 "baecece31a9937de2deaa1196c55179bd1240d08d3b7742b4790eeb5b44c176c"

    def install
      bin.install "ezshare-sync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.1/ezshare-sync_1.1.1_linux_amd64.tar.gz"
      sha256 "33c7d725ad11e6d8479accc378fe30b0f5ea86a89ea33792c7d2fbb00862de7d"
      def install
        bin.install "ezshare-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/ezshare-sync/releases/download/v1.1.1/ezshare-sync_1.1.1_linux_arm64.tar.gz"
      sha256 "6b9b7ab5443931352c2386f448b54d5768ba585425d2cf0f4468d084489efaff"
      def install
        bin.install "ezshare-sync"
      end
    end
  end

  service do
    run [opt_bin/"ezshare-sync"]
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/ezshare-sync -h", 0)
  end
end
