# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mqtt2cmd < Formula
  desc "MQTT to command-line applications gateway."
  homepage "https://github.com/haimgel/mqtt2cmd"
  version "0.0.1"

  on_macos do
    url "https://github.com/haimgel/mqtt2cmd/releases/download/0.0.1/mqtt2cmd_0.0.1_Darwin_all.tar.gz"
    sha256 "b6bd0b060a280d18f517494544912dc1fb35d0f74393501e67a3cd8d309ac95d"

    def install
      bin.install "mqtt2cmd"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/0.0.1/mqtt2cmd_0.0.1_Linux_arm64.tar.gz"
      sha256 "a22b62e83e8d1849ffbecb37bcddb5375c83706cd0c38e0d5cb9f284874106e7"

      def install
        bin.install "mqtt2cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/0.0.1/mqtt2cmd_0.0.1_Linux_x86_64.tar.gz"
      sha256 "358d1cc6143e60b5cfec1f5317d4084544b9cc0527d28a239ca1e4b1a7d1e77a"

      def install
        bin.install "mqtt2cmd"
      end
    end
  end

  service do
    run: mqtt2cmd
  end

  test do
    assert_match /help string/, shell_output("#{bin}/mqtt2cmd -h", 0)
  end
end
