# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mqtt2cmd < Formula
  desc "MQTT to command-line applications gateway."
  homepage "https://github.com/haimgel/mqtt2cmd"
  version "0.1.2"

  on_macos do
    url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.2/mqtt2cmd_0.1.2_Darwin_all.tar.gz"
    sha256 "660457dda70f6e299223292ff8fb92a92be3bdb2c07e2f67e08e8f8ed931d4c7"

    def install
      bin.install "mqtt2cmd"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.2/mqtt2cmd_0.1.2_Linux_arm64.tar.gz"
      sha256 "9792b4202578d1522616a751f5b895fe23219fdbdd3df224f191eb3d9e7bc04f"

      def install
        bin.install "mqtt2cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.2/mqtt2cmd_0.1.2_Linux_x86_64.tar.gz"
      sha256 "cdab8faf85d96c2d5ffe6f37e7459a629c6b3a812a33ce995510a12c0bde9c97"

      def install
        bin.install "mqtt2cmd"
      end
    end
  end

  service do
    run [opt_bin/"mqtt2cmd"]
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/mqtt2cmd -h", 0)
  end
end
