# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mqtt2cmd < Formula
  desc "MQTT to command-line applications gateway."
  homepage "https://github.com/haimgel/mqtt2cmd"
  version "0.1.5"

  on_macos do
    url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.5/mqtt2cmd_0.1.5_Darwin_all.tar.gz"
    sha256 "ce5be85c3e54d553075001cd1a8430681c098f0c22d6835548a0be1891eb5cee"

    def install
      bin.install "mqtt2cmd"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.5/mqtt2cmd_0.1.5_Linux_arm64.tar.gz"
      sha256 "6a6f09135c9207db5f03c59ff0675d2a5e190972c037d44e05e47086dc7f5bc2"

      def install
        bin.install "mqtt2cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haimgel/mqtt2cmd/releases/download/v0.1.5/mqtt2cmd_0.1.5_Linux_x86_64.tar.gz"
      sha256 "649437929afc7a6adf5b7e6e5d907ff3f86128c93ecd8eb6cf6101808cfb2f4f"

      def install
        bin.install "mqtt2cmd"
      end
    end
  end

  service do
    run [opt_bin/"mqtt2cmd"]
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/mqtt2cmd -h", 0)
  end
end
