# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackStatus < Formula
  desc "Set Slack status to predefined values from a command line."
  homepage "https://github.com/haimgel/slack-status-go"
  version "0.2.1"

  on_macos do
    url "https://github.com/haimgel/slack-status-go/releases/download/0.2.1/slack-status_0.2.1_darwin_all.tar.gz"
    sha256 "42398efe0ef9af8ef4204e0ef50cc754dbcd23fdfe3bb0419bee1d2a242b1e04"

    def install
      bin.install "slack-status"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/slack-status-go/releases/download/0.2.1/slack-status_0.2.1_linux_arm64.tar.gz"
      sha256 "9fb477ac631e353adaf1b6ae6dc4fd643a132980ba8edb265ea7b916d267fc09"

      def install
        bin.install "slack-status"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haimgel/slack-status-go/releases/download/0.2.1/slack-status_0.2.1_linux_amd64.tar.gz"
      sha256 "9b3caf569915f7223d229f01e735a4ae48360277be108d05304f2b552f114d8a"

      def install
        bin.install "slack-status"
      end
    end
  end

  test do
    assert_match /Set Slack status/, shell_output("#{bin}/slack-status -h", 0)
  end
end
