# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackStatus < Formula
  desc "Set Slack status to predefined values from a command line."
  homepage "https://github.com/haimgel/slack-status-go"
  version "0.3.4"

  on_macos do
    url "https://github.com/haimgel/slack-status-go/releases/download/0.3.4/slack-status_0.3.4_darwin_all.tar.gz"
    sha256 "1465381afe35b74c623eaa3592c231466722915b40b35fbdf0a6bd0f48f26c06"

    def install
      bin.install "slack-status"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/slack-status-go/releases/download/0.3.4/slack-status_0.3.4_linux_amd64.tar.gz"
      sha256 "3cea7338a4612b9bd89d9a44019958cac3c0e15165f3c82df5c76c4513259150"
      def install
        bin.install "slack-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haimgel/slack-status-go/releases/download/0.3.4/slack-status_0.3.4_linux_arm64.tar.gz"
      sha256 "10fcca6ae0684f96ed397659985a6596dcdd84c85a86834d913aa6408fb28525"
      def install
        bin.install "slack-status"
      end
    end
  end

  test do
    assert_match /Set Slack status/, shell_output("#{bin}/slack-status -h", 0)
  end
end
